### ISSUE TITLE
yarn run test fails 2nd

### ISSUE THREAD

**Issue by alepi** [etesync/etebase-js#40]
> You need to run the server in debug mode for the tests to work.
> 
> Closing as the question was answered.
> 
> 

_Originally posted by @tasn in https://github.com/etesync/etebase-js/issues/39#issuecomment-988215140_

I did not find the usual button to reopen the issue on #39 so I created a new one. When running the server in debug mode I still get failures:

Test Suites: 3 failed, 2 passed, 5 total
Tests:       17 failed, 1 skipped, 18 passed, 36 total
Snapshots:   0 total
Time:        6.365s
Ran all test suites.
error Command failed with exit code 1.

Most errors are about trying to mkdir the home directory ( which already exists ):

500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
Traceback (most recent call last):
  File "FILTERED/etebase/etebase/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
[...]
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 5 more times]
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 45] Operation not supported: <MY_HOME_DIRECTORY>

**Comment by tasn** [comment]
I think you should be able to reopen, weird that you can't, but anyhow you can comment and then I can reopen.


As for the issue: weird. Have you set the data dir correctly in the settings? Talk a look at the README.

**Comment by alepi** [comment]
Some of these tests fail on the Mac but pass on Linux. No need to fix for me now.

**Comment by tasn** [comment]
Weird.
