### ISSUE TITLE
Duplicate chunks throw an error

### ISSUE THREAD

**Issue by cooper667** [etesync/etebase-js#51]
If you `setContent` with repetitive data on a collection, an error is thrown when trying to get that content again. 

```
 TypeError: Cannot read properties of undefined (reading 'length')
    at reduce (/etebase-js/src/Crypto.ts:36:49)
    at Array.reduce (<anonymous>)
    at concatArrayBuffersArrays (/etebase-js/src/Crypto.ts:36:26)
    ...
```

It looks like the index list and/or chunks created [here](https://github.com/etesync/etebase-js/blob/master/src/EncryptedModels.ts#L317) are the issue (the indices are pointers at the original chunks array, but the chunks array is mutated here, so the pointers are incorrect?)

The following tests illustrate the issue (large files are fine, small files are fine, but _repetitive_ data (that would result in chunks that would be deduplicated) throws the error

```typescript
describe.only("chunking files", () => {
  it("Duplicate Chunks", async () => {
    const collectionManager = etebase.getCollectionManager();
    const col = await collectionManager.create(colType, {}, "");

    const buf = randomBytesDeterministic(10 * 1024, new Uint8Array(32)); // 10kb of psuedorandom data
    const content = JSON.stringify([buf, buf, buf, buf]);

    await col.setContent(content);

    await collectionManager.transaction(col);
    const decryptedContent = await col.getContent(); // <---
    /*
  TypeError: Cannot read properties of undefined (reading 'length')
    at reduce (/etebase-js/src/Crypto.ts:36:49)
    at Array.reduce (<anonymous>)
    at concatArrayBuffersArrays (/etebase-js/src/Crypto.ts:36:26)
    ...
  */

    const out = to_string(decryptedContent);
    expect(out).toEqual(content);
  });

  it("Regular Chunks", async () => {
    const collectionManager = etebase.getCollectionManager();
    const col = await collectionManager.create(colType, {}, "");

    const buf = randomBytesDeterministic(100 * 1024, new Uint8Array(32));
    const content = JSON.stringify(buf);

    await col.setContent(content);

    await collectionManager.transaction(col);
    const decryptedContent = await col.getContent();

    const out = to_string(decryptedContent);
    expect(out).toEqual(content);
  });
  
  it("Small file, no chunks", async () => {
    const collectionManager = etebase.getCollectionManager();
    const col = await collectionManager.create(colType, {}, "");

    const buf = randomBytesDeterministic(10, new Uint8Array(32));
    const content = JSON.stringify(buf);

    await col.setContent(content);

    await collectionManager.transaction(col);
    const decryptedContent = await col.getContent();

    const out = to_string(decryptedContent);
    expect(out).toEqual(content);
  });
});
```

I'll do a PR with a fix shortly

**Comment by tasn** [comment]
Let me know once the PR is ready and I'll take a look. I wonder if this also affects the Rust code (and thus every other library).

**Comment by tasn** [comment]
Did you mean to close this?

**Comment by cooper667** [comment]
No! I didn't think merging the PR into a fork would close it.

**Comment by Skycoder42** [comment]
What is the state of this? This is a serious issue that can lead to data corruption. I have encountered it at least once in a real life scenario. I really think this needs to be fixed.
